title: "Surgical Scene Segmentation Using Semantic Image Synthesis with a Virtual Surgery Environment"
description: "A comprehensive technical report on surgical scene segmentation using semantic image synthesis with a virtual surgery environment."
baseurl: ""
url: "https://sisvse.github.io"
timezone: "UTC"
header_pages: []
